### ISSUE TITLE
LINE機能実装に関して

### ISSUE THREAD

**Issue by SatoNozomi44** [SatoNozomi44/Tra_gori#152]
# 概要
## 実装目標の機能内容
- ログイン中のプロフィール画面からLINE連携を行い、『ともだち追加』ボタンをクリックする事でWebアプリの公式アカウントをともだち追加する事が出来る。
- **`training_records`** テーブルの **`sport_content`** カラムに値が保存されていない場合、夜9時にLINE通知が送信される。
- LINE通知に関しては、 **`users_profiles`** テーブルの **`line_notify_on`** カラムでtrue/falseで管理するようにする。

　
## 現在の状況
まずLINE認証機能を実装する必要があると思い、sorceryのExternalモジュールを使用してLINE認証を実装中です。

その際、記事を参考に【 LINE Developersの登録→新規チャネル作成 】と【 Externalモジュールの設定 】を行い、LINE認証を行おうとしたところ下記のように400エラーが発生してしまいます。

![image](https://github.com/SatoNozomi44/Tra_gori/assets/130850494/ba027927-c127-4379-92e5-77d33f25453f)

　
ターミナル・コンソール等を確認しているのですが原因が分からず手詰まりな状態です….💦

```
Started GET "/users_profiles" for 127.0.0.1 at 2024-02-13 22:48:41 +0900
Processing by UsersProfilesController#show as HTML
  User Load (13.0ms)  SELECT "users".* FROM "users" WHERE "users"."id" = $1 LIMIT $2  [["id", 1], ["LIMIT", 1]]
  WeightRecord Load (33.9ms)  SELECT "weight_records".* FROM "weight_records" WHERE "weight_records"."user_id" = $1 ORDER BY "weight_records"."created_at" DESC LIMIT $2  [["user_id", 1], ["LIMIT", 1]]
  ↳ app/controllers/users_profiles_controller.rb:5:in `show'
  WeightRecord Load (0.3ms)  SELECT "weight_records".* FROM "weight_records" WHERE "weight_records"."user_id" = $1 AND "weight_records"."created_at" BETWEEN $2 AND $3 LIMIT $4  [["user_id", 1], ["created_at", "2024-02-13 00:00:00"], ["created_at", "2024-02-13 23:59:59.999999"], ["LIMIT", 1]]
  ↳ app/models/weight_record.rb:5:in `weight_record_for_day'
  WeightRecord Pluck (0.3ms)  SELECT "weight_records"."created_at", "weight_records"."weight" FROM "weight_records" WHERE "weight_records"."user_id" = $1 ORDER BY "weight_records"."created_at" ASC  [["user_id", 1]]
  ↳ app/controllers/users_profiles_controller.rb:8:in `show'
  Rendering layout layouts/application.html.erb
  Rendering users_profiles/show.html.erb within layouts/application
  TrainingRecord Count (0.3ms)  SELECT COUNT(*) FROM "training_records" WHERE "training_records"."user_id" = $1  [["user_id", 1]]
  ↳ app/views/users_profiles/show.html.erb:19
  UsersProfile Load (0.2ms)  SELECT "users_profiles".* FROM "users_profiles" WHERE "users_profiles"."user_id" = $1 LIMIT $2  [["user_id", 1], ["LIMIT", 1]]
  ↳ app/views/users_profiles/show.html.erb:23
  Authentication Load (0.5ms)  SELECT "authentications".* FROM "authentications" WHERE "authentications"."user_id" = $1 AND "authentications"."provider" = $2  [["user_id", 1], ["provider", "line"]]
  ↳ app/models/user.rb:29:in `line_auth'
  Rendered weight_records/_new.html.erb (Duration: 0.8ms | Allocations: 396)
  Rendered users_profiles/show.html.erb within layouts/application (Duration: 6.3ms | Allocations: 3442)
  NumberOfBanana Load (0.3ms)  SELECT "number_of_bananas".* FROM "number_of_bananas" WHERE "number_of_bananas"."user_id" = $1 LIMIT $2  [["user_id", 1], ["LIMIT", 1]]
  ↳ app/views/shared/_login_header.html.erb:10
  Rendered shared/_login_header.html.erb (Duration: 1.8ms | Allocations: 1529)
  Rendered shared/_flash_message.html.erb (Duration: 0.0ms | Allocations: 18)
  Rendered shared/_footer.html.erb (Duration: 0.1ms | Allocations: 137)
  Rendered layout layouts/application.html.erb (Duration: 14.8ms | Allocations: 9509)
Completed 200 OK in 77ms (Views: 14.1ms | ActiveRecord: 48.7ms | Allocations: 14034)


Started GET "/oauth/line" for 127.0.0.1 at 2024-02-13 22:48:44 +0900
Processing by OauthsController#oauth as HTML
  Parameters: {"provider"=>"line"}
Redirected to https://access.line.me/oauth2/v2.1/authorize?client_id&display&redirect_uri=https%3A%2F%2Flocalhost%3A9292%2Foauth%2Fcallback%3Fprovider%3Dline&response_type=code&scope=profile&state=2814896e97a3b1e0fa20ff52e515cc5d
Completed 302 Found in 4ms (ActiveRecord: 0.0ms | Allocations: 993)
```

　
## コード内容
- db/schema.rb
```
ActiveRecord::Schema[7.0].define(version: 2024_02_09_091647) do
  # These are extensions that must be enabled in order to support this database
  enable_extension "plpgsql"

  create_table "authentications", force: :cascade do |t|
    t.integer "user_id", null: false
    t.string "provider", null: false
    t.string "uid", null: false
    t.datetime "created_at", null: false
    t.datetime "updated_at", null: false
    t.index ["provider", "uid"], name: "index_authentications_on_provider_and_uid"
  end

  create_table "users", force: :cascade do |t|
    t.string "name", null: false
    t.string "email", null: false
    t.string "crypted_password"
    t.string "salt"
    t.datetime "created_at", null: false
    t.datetime "updated_at", null: false
    t.string "reset_password_token"
    t.datetime "reset_password_token_expires_at"
    t.datetime "reset_password_email_sent_at"
    t.integer "access_count_to_reset_password_page", default: 0
    t.integer "role", default: 0, null: false
    t.index ["email"], name: "index_users_on_email", unique: true
    t.index ["reset_password_token"], name: "index_users_on_reset_password_token"
  end
end
```

- app/models/user.rb
```
class User < ApplicationRecord
  authenticates_with_sorcery!
  
  has_many :authentications, dependent: :destroy

  accepts_nested_attributes_for :authentications
 
  validates :name, presence: true, length: { minimum: 2, maximum: 50 }
  validates :email, uniqueness: true, presence: true
  validates :password, length: { minimum: 5 }, if: -> { new_record? || changes[:crypted_password] }
  validates :password, format: { with: /\A(?=.*[a-zA-Z])(?=.*[0-9]).{5,}\z/ }, if: -> { new_record? || changes[:crypted_password] }
  validates :password, confirmation: true, if: -> { new_record? || changes[:crypted_password] }
  validates :password_confirmation, presence: true, if: -> { new_record? || changes[:crypted_password] }
  validates :reset_password_token, uniqueness: true, allow_nil: true

  def google_auth
    authentications.where(provider: "google").present?
  end

  def line_auth
    authentications.where(provider: "line").present?
  end
end
```

- app/controllers/oauths_controller.rb
```
class OauthsController < ApplicationController
  skip_before_action :require_login
  
  def oauth
    #指定されたプロバイダの認証ページにユーザーをリダイレクトさせる
    login_at(auth_params[:provider])
  end

  def callback
    provider = auth_params[:provider]
    # 既存のユーザーをプロバイダ情報を元に検索し、存在すればログイン
    if (@user = login_from(provider))
      flash[:success] = t('.login_success', provider: provider.titleize)
      redirect_to training_records_path
    else
      begin
        # ユーザーが存在しない場合はプロバイダ情報を元に新規ユーザーを作成し、ログイン
        @user = create_from(provider)
        reset_session # セキュリティ上の理由からセッションをリセット
        auto_login(@user) # Sorceryのauto_loginメソッドでユーザーを自動ログイン
        flash[:success] = t('.login_success', provider: provider.titleize)
        redirect_to training_records_path
      rescue
        flash[:alert] = t('.login_failure', provider: provider.titleize)
        redirect_to root_path
      end
    end
  end

  private

  def auth_params
    params.permit(:code, :provider, :error, :state)
  end

  def signup_and_login(provider)
    @user = create_from(provider)
    reset_session
    auto_login(@user)
  end
end
```

- config/initializers/sorcery.rb
```
Rails.application.config.sorcery.submodules = [:external]

Rails.application.config.sorcery.configure do |config|

    (中略)

    config.external_providers = %i[google line]

    (中略)

    config.line.key = Rails.application.credentials.dig(:line, :line_client_id)         # line_keyはcredentialsで管理しています
    config.line.secret = Rails.application.credentials.dig(:line, :line_secret_idt)   # line_secretはcredentialsで管理しています
    config.line.callback_url = Settings.sorcery[:line_callback_url]               # line_callback_urlはconfig gemで管理しています
    config.line.scope = 'profile'

    (以下略)
end
```

　
### 参考にした記事
https://qiita.com/tarakish/items/a4c73104375878ad61c5

https://qiita.com/MrTom_2020/items/e97a046079b5f6bc040e

　
### プルリクエスト
https://github.com/SatoNozomi44/Tra_gori/pull/151

**Comment by Tsuchiya2** [comment]
対応ありがとうございます。
そうですね。。mkcertは使ったことが無いので、私としてはngrokを共有しておきますね。

https://qiita.com/mininobu/items/b45dbc70faedf30f484e

（あとNotionへ飛んで確認するのが手間なので、↑の概要のところに内容はっておいてもらえると助かります）

---

> LINE 404 Bad Request

↑の画面が出るとのことですが、LINE DevelopersのLINEログイン設定・コールバックURLは適切なものになっているか確認したりしてみましょう。ngrokだと以下の画像の赤線の部分を使用します。また、公式ドキュメントや他の類似エラーを調べたりしましょう。

<img width="952" alt="スクリーンショット 2024-02-14 12 11 10" src="https://github.com/SatoNozomi44/Tra_gori/assets/61481161/f90b55e0-fe7c-4a6e-9618-b41f2c67a693">
<img width="952" alt="スクリーンショット 2024-02-14 12 11 17" src="https://github.com/SatoNozomi44/Tra_gori/assets/61481161/971dc1a7-e795-4603-9579-21efafccee10">

さっとGoogle検索しただけでも似たようなケースの記事等が見つかりるので、調べる努力も合わせて行うようにしましょう。
- https://qiita.com/ICU1234/items/1a6c2e9729aa64a9858f
- https://support.ec-force.com/hc/ja/articles/4407310334361-LINE-ID%E9%80%A3%E6%90%BA%E3%81%8C%E6%AD%A3%E5%B8%B8%E3%81%AB%E5%8B%95%E4%BD%9C%E3%81%97%E3%81%AA%E3%81%84%E5%A0%B4%E5%90%88%E3%81%AE%E3%82%88%E3%81%8F%E3%81%82%E3%82%8B%E4%BA%8B%E4%BE%8B

**Comment by SatoNozomi44** [comment]
ご確認、ありがとうございます！🙇‍♂️
土屋さんが共有して下さった記事を参考に、`ngrok`の設定を行い問題無く開発環境のSSL化が出来ました。

URI：https://e7cc-49-96-13-63.ngrok-free.app

![image](https://github.com/SatoNozomi44/Tra_gori/assets/130850494/1cd77fe5-291b-497b-a6a1-f5fae5565427)

　
『 **LINE DevelopersコールバックURLの設定** 』『 **`sorcery.rb` ExternalでのコールバックURLの設定** 』これらに関しても、ngrokでのURIに変更してあります。

![image](https://github.com/SatoNozomi44/Tra_gori/assets/130850494/a05020f4-2dc6-4038-ab42-5f5ef5e7f607)

- config/settings/development.rb (`callback_url`は`config Gem`で環境ごとに管理しています)
```
sorcery:
  google_callback_url: 'http://localhost:3000/oauth/callback?provider=google'
  line_callback_url: 'https://e7cc-49-96-13-63.ngrok-free.app/oauth/callback?provider=line'
default_url_options:
  host: "localhost:3000"
``` 

　
これらの設定を見直して、再度LINE認証を試みたのですが先ほどとエラー画面が変わりません💦

![image](https://github.com/SatoNozomi44/Tra_gori/assets/130850494/59bab2f6-b5ee-4c26-921e-4eecfeff5aa8)

エラー画面を確認するに、リクエスト内の`client_id (チャネルID)`がnullであると表示されているので、『チャネルID』『チャネルシークレット』が間違っているのか再度確認したのですが、特に間違いは無かったです。

**Comment by Tsuchiya2** [comment]
```
sorcery:
  google_callback_url: 'http://localhost:3000/oauth/callback?provider=google'
  line_callback_url: 'https://e7cc-49-96-13-63.ngrok-free.app/oauth/callback?provider=line'
default_url_options:
  host: "localhost:3000"
```

開発環境でRailsコンソールを立ち上げて↑の値が返ってくるか確認してみていただけますか？
あと現在何が原因で400 Bad Requestページが出てしまうのか調べたり、仮説立てしたことなどを共有いただけますか？

> エラー画面を確認するに、リクエスト内のclient_id (チャネルID)がnullであると表示されているので、『チャネルID』『チャネルシークレット』が間違っているのか再度確認したのですが、特に間違いは無かったです。

↑確認されたとのことですが、`リクエスト内のclient_id (チャネルID)がnullであると表示`されるのは変わらずですかね？もしそうであれば、なぜnullになるのか調査して修正等を試してみていただけますか？

**Comment by SatoNozomi44** [comment]
開発環境でRailsコンソールを立ち上げ、**`callback_url`**・環境変数の値が返ってくるか確認してみたところ、LINE認証に関する環境変数の値のみが返ってきていない状態でした。

原因について、一つこちらの抜けがありました...
　
## 原因
以前、中井さんの提案で、『進捗が同じメンバー同士でコードレビューを行う』という開発の進め方を行っていました。

その際、レビュワーに **`master_key`** を都度渡す方法ではなく、開発環境用に **`development.yml`** を作成して **`development.key`** を渡すようにしていたのですが...

今回LINE認証に関する環境変数を、 **`credentials.yml`** のみに追加しており **`development.yml`** には追加をしていませんでした💦
　
## 対策
**`EDITOR=vim bin/rails credentials:edit -e development`** vimで **`development.yml`** を開き環境変数を設定後、ローカルで確認したところ、問題なくログイン画面が表示されました...！

![image](https://github.com/SatoNozomi44/Tra_gori/assets/130850494/9a27f442-f6c9-48a4-ad7f-8c2b3e35a523)

## 追加で発生中のエラーについて
現状、ログイン画面への遷移までは行えています。
しかし、連携しようとすると例外が発生してしまう状態です。

これに関しては外部認証のロジックを現在修正中です。
　
こちらに関して、エラーが解決出来なそうであれば再度ご相談したいのですが...🙇‍♂️
こちらのissueで連絡する形で問題ないでしょうか？
それとも、別でissueを立ててご連絡した方が良いでしょうか？🤔

**Comment by Tsuchiya2** [comment]
1つ前に進んだようで良かったです！
そうですね。別途issueを立ててご連絡をお願いいたします。

**Comment by SatoNozomi44** [comment]
了解しました！
別途issue立てましたら、Mattermostにてご連絡します🙇‍♂️
